print("Welcome to the band name generator.")
print("What's the name of the city you grew up in?")
city = input()
print("What's the name of your pet?")
pet = input()
print("Your band name could be: " + city + " " + pet)